#!/bin/bash
#PBS -M vysusilova.petra.m@gmail.com # specify recipient's email; if this option is not used, your registered email will be used
#PBS -m abe # send mail when the job begins (b), aborts (a) or ends (e)
#arguments parsers (dont pass equal sign as a value!!)
#source: https://unix.stackexchange.com/questions/129391/passing-named-arguments-to-shell-scripts
# potrebuju: exp, layout name, seed, frame_stacking_mode,vf_coef
for ARGUMENT in "$@"
do
   KEY=$(echo $ARGUMENT | cut -f1 -d=)

   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"

   export "$KEY"="$VALUE"
done

declare -A def_vals
def_vals=( [file]="./coding/PPO/overcooked_pytorch_stable_baselines/overcooked_ai/src/overcooked_ai_py/diverse_population/scripts/script.sh" [walltime]="02:50:00" [home_dir]="/storage/plzen1/home/ayshi")
for i in "${!def_vals[@]}"
do
  if [[ -z "${!i}" ]]; then declare "${i}"="${def_vals[$i]}"; fi
done

echo "home set to: $home_dir"
export $home_dir
job_name="${exp}_${layout_name}_${frame_stacking_mode}"
echo $job_name

#cd "$home_dir"/coding/pbs-tools
res_dir="$home_dir"/coding/results
echo "results can be found here: $res_dir"
date_name=$(date +%m%d-%H%M)
echo "walltime:" $walltime

hours=$(echo $walltime | cut -d: -f1) 

if [ ${hours} -gt 23 ]; then
	echo "dlouha fronta"
	fronta="gpu_long"
else
        echo "job pobezi v normalni fronte"
	fronta="gpu"
fi

for arg in "$@"; do
  shift
  echo $arg
  if [[ $arg != walltime* ]] && [[ $arg != file* ]] ;
  then
    set -- "$@" "$arg"
  fi
done

params=$@
if [ -z "$file" ]; then echo "I can't read your mind, provide file=value parameter please.";
else
	echo $fronta
	echo "I will run $file"
	echo "params:"
        echo $params
	qsub -m abe -M vysusilova.petra.m@gmail.com -N "$exp"_"$date_name" -e "$res_dir" -o "$res_dir" -l select=1:ncpus=4:ngpus=1:mem=17gb:scratch_local=4gb -q $fronta -l walltime=$walltime -v home_dir=$home_dir,params="$params" "$home_dir"/"$file" 
fi
