#!/bin/bash
#PBS -M vysusilova.petra.m@gmail.com # specify recipient's email; if this option is not used, your registered email will be used
#PBS -m abe # send mail when the job begins (b), aborts (a) or ends (e)
#arguments parsers (dont pass equal sign as a value!!)
#source: https://unix.stackexchange.com/questions/129391/passing-named-arguments-to-shell-scripts
# potrebuju: exp, layout name, seed, frame_stacking_mode,vf_coef
for ARGUMENT in "$@"
do
   KEY=$(echo $ARGUMENT | cut -f1 -d=)

   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"

   export "$KEY"="$VALUE"
done


declare -A def_vals
def_vals=( [walltime]="02:50:00" [home_dir]="/storage/plzen1/home/ayshi")
for i in "${!def_vals[@]}"
do
  if [[ -z "${!i}" ]]; then declare "${i}"="${def_vals[$i]}"; fi
done

oldIFS=$IFS
IFS=","
params="$*"
IFS=$oldIFS

echo "home set to: $home_dir"

job_name="${exp}_${layout_name}_${frame_stacking_mode}"
echo $job_name

#cd "$home_dir"/coding/pbs-tools
res_dir="$home_dir"/coding/results
echo "results can be found here: $res_dir"
date_name=$(date +%m%d-%H%M)
echo "walltime:" $walltime

hours=$(echo $walltime | cut -d: -f1) 

if [ ${hours} -gt 23 ]; then
	echo "je vetsi"
	fronta="gpu_long"
else
        echo "job pobezi v normalni fronte"
	fronta="gpu"
fi

if [ -z "$file" ]; then echo "I can't read your mind, provide file=value parameter please.";
else 
	echo "frame stacking and trained models:" $frame_stacking
	echo $trained_models
	echo $fronta
	echo "I will run $file"
	echo "params:"
  echo $params
	qsub -m abe -M vysusilova.petra.m@gmail.com -N "$exp"_"$date_name" -e "$res_dir" -o "$res_dir" -l select=1:ncpus=4:ngpus=1:mem=15gb:scratch_local=4gb -q $fronta -l walltime=$walltime -- "$home_dir"/"$file" $@
#	qsub -m abe -M vysusilova.petra.m@gmail.com -N "$exp"_"$date_name" -e "$res_dir" -o "$res_dir" -l select=1:ncpus=4:ngpus=1:mem=17gb:scratch_local=4gb -q $fronta -l walltime=$walltime -v home_dir=$home_dir,layout_name=$layout_name,num_workers=$num_workers,trained_models=$trained_models,exp=$exp,init_SP_agents=3,delay_shared_rewards=False,mode=$mode,kl_diff_bonus_reward_coef=0.0,kl_diff_bonus_reward_clip=0.0,kl_diff_loss_coef=0.0,kl_diff_loss_clip=0.0,seed=$seed,n_sample_partners=$n_sample_partners,frame_stacking=$frame_stacking,frame_stacking_mode=$frame_stacking_mode,vf_coef=$vf_coef,execute_final_eval=$execute_final_eval "$home_dir"/"$file"
fi
