#!/bin/bash

#arguments parsers (dont pass equal sign as a value!!)
#source: https://unix.stackexchange.com/questions/129391/passing-named-arguments-to-shell-scripts
# potrebuju: exp, layout name, seed, frame_stacking_mode,vf_coef
for ARGUMENT in "$@"
do
   KEY=$(echo $ARGUMENT | cut -f1 -d=)

   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"
   
   export "$KEY"="$VALUE"
done



#declare -A def_vals
#def_vals=([trained_models]=11 [mode]="POP" [frame_stacking]=4 [vf_coef]=0.1 [frame_stacking_mode]="channels")
#for i in "${!def_vals[@]}"
#do
#  if [[ -z "${!i}" ]]; then declare "${i}"="${def_vals[$i]}"; fi
#done

firsttime=yes
for i in "$@" 
do
    test "$firsttime" && set -- && unset firsttime
    test "${i%%file*}" && set -- "$@" "$i"
done

#IFS=_ ; echo "$*"

oldIFS=$IFS
IFS=","
params="$*"
IFS=$oldIFS
#home dir must be set correctly
if [ -z "$home_dir" ]; then home_dir="/storage/plzen1/home/ayshi"; fi
echo "home set to: $home_dir"

job_name="${exp}_${layout_name}_${frame_stacking_mode}_train"
echo $job_name

#cd "$home_dir"/coding/pbs-tools
res_dir="$home_dir"/coding/results
echo "results can be found here: $res_dir"
date_name=$(date +%m%d-%H%M)

if [ -z "$file" ]; then echo "I can't read your mind, provide file=value parameter please.";
else 
	#echo "frame stacking and trained models:" $frame_stacking
	#echo $trained_models
	echo "I will run $file"
	echo $params
	#qsub -N "$date_name"_"$exp" -e "$res_dir" -o "$res_dir" -l select=1:ncpus=3:ngpus=1:mem=15gb:scratch_local=4gb -q gpu -l walltime=02:50:00 -v $params "$home_dir"/"$file"

fi
