#!/bin/bash

#arguments parsers (dont pass equal sign as a value!!)
#source: https://unix.stackexchange.com/questions/129391/passing-named-arguments-to-shell-scripts
for ARGUMENT in "$@"
do
   KEY=$(echo $ARGUMENT | cut -f1 -d=)

   KEY_LENGTH=${#KEY}
   VALUE="${ARGUMENT:$KEY_LENGTH+1}"

   export "$KEY"="$VALUE"
done

#home dir must be set correctly
if [ -z "$home_dir" ]; then home_dir="/storage/plzen1/home/ayshi"; fi
echo "home set to: $home_dir"

cd "$home_dir"/coding/pbs-tools
res_dir="$home_dir"/coding/results
echo "results can be found here: $res_dir"
date_name=$(date +%m%d-%H%M)

if [ -z "$file" ]; then echo "I can't read your mind, provide file=value parameter please.";
else 
	echo "I will run $file"
	qsub -m ba -N "$date_name"_"$exp" -e "$res_dir" -o "$res_dir" -l select=1:ncpus=4:ngpus=1:mem=14gb:scratch_local=4gb -q gpu -l walltime=00:50:00 -v layout_name=$layout_name,trained_models=1,exp=$exp,init_SP_agents=3,delay_shared_rewards=False,mode="SP",kl_diff_bonus_reward_coef=0.0,kl_diff_bonus_reward_clip=0.0,kl_diff_loss_coef=0.0,kl_diff_loss_clip=0.0,seed=$seed,home_dir=$home_dir,n_sample_partners=-1 \
"$home_dir"/"$file"

fi
